repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.2.0
    hooks:
    -   id: add-trailing-comma

  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
    -   id: autoflake
        args: [
            --in-place,
            --ignore-init-module-imports,
            --remove-unused-variables,
        ]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
    - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        args: [
          --config=.flake8,
          --max-line-length=120,
        ]
        exclude: .git|__pycache__
        additional_dependencies:
          - flake8-builtins>=1.5.3
          - flake8-commas>=2.0.0
          - flake8-debugger>=4.0.0
          - flake8-comprehensions>=3.3.1
          - flake8-eradicate>=1.0.0
          - dlint>=0.11.0
