# Generated by Django 5.2.4 on 2025-08-06 01:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_choice', models.CharField(max_length=50, verbose_name='Выбор категории')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceOperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type_choice', models.CharField(max_length=50, verbose_name='Выбор типа операции')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_choice', models.CharField(max_length=50, verbose_name='Выбор статуса')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_choice', models.CharField(max_length=50, verbose_name='Выбор подкатегории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dds.choicecategory', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='DDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dds.choicecategory', verbose_name='Категория')),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dds.choiceoperationtype', verbose_name='Тип операции')),
                ('status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='dds.choicestatus', verbose_name='Статус')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dds.choicesubcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Движение денежных средств',
            },
        ),
    ]
