# Generated by Django 5.2.5 on 2025-08-09 23:13

import datetime
import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('dds', '0001_initial'), ('dds', '0002_alter_dds_subcategory'), ('dds', '0003_alter_choicecategory_options_and_more'), ('dds', '0004_alter_dds_subcategory'), ('dds', '0005_alter_dds_category'), ('dds', '0006_alter_dds_category_alter_dds_subcategory'), ('dds', '0007_rename_category_choice_choicecategory_choice_value_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_choice', models.CharField(max_length=50, verbose_name='Выбор категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ChoiceOperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_value', models.CharField(max_length=50, verbose_name='Тип операции')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='ChoiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_value', models.CharField(max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='ChoiceSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_value', models.CharField(max_length=50, verbose_name='Подкатегория')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dds.choicecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.AddField(
            model_name='choicecategory',
            name='operation_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='dds.choiceoperationtype', verbose_name='Тип операции'),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='choicecategory',
            old_name='category_choice',
            new_name='choice_value',
        ),
        migrations.AlterField(
            model_name='choicecategory',
            name='choice_value',
            field=models.CharField(max_length=50, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='DDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('category', smart_selects.db_fields.ChainedForeignKey(chained_field='operation_type', chained_model_field='operation_type', on_delete=django.db.models.deletion.PROTECT, to='dds.choicecategory', verbose_name='Категория')),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dds.choiceoperationtype', verbose_name='Тип операции')),
                ('status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='dds.choicestatus', verbose_name='Статус')),
                ('subcategory', smart_selects.db_fields.ChainedForeignKey(chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.PROTECT, to='dds.choicesubcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Движение денежных средств',
                'verbose_name_plural': 'Движения денежных средств',
            },
        ),
    ]
