# Generated by Django 5.2.5 on 2025-08-08 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0002_alter_dds_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choicecategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='choiceoperationtype',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.AlterModelOptions(
            name='choicestatus',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='choicesubcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='dds',
            options={'verbose_name': 'Движение денежных средств', 'verbose_name_plural': 'Движения денежных средств'},
        ),
        migrations.AddField(
            model_name='choicecategory',
            name='operation_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='dds.choiceoperationtype', verbose_name='Тип операции'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choicecategory',
            name='category_choice',
            field=models.CharField(max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='choiceoperationtype',
            name='operation_type_choice',
            field=models.CharField(max_length=50, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='choicestatus',
            name='status_choice',
            field=models.CharField(max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='choicesubcategory',
            name='subcategory_choice',
            field=models.CharField(max_length=50, verbose_name='Подкатегория'),
        ),
    ]
