# Generated by Django 5.2.5 on 2025-08-08 15:14

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0003_alter_choicecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dds',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='operation_type', chained_model_field='operation_type', on_delete=django.db.models.deletion.PROTECT, to='dds.choicesubcategory', verbose_name='Подкатегория'),
        ),
    ]
