# Generated by Django 5.2.5 on 2025-08-08 15:16

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0004_alter_dds_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dds',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.PROTECT, to='dds.choicecategory', verbose_name='Категория'),
        ),
    ]
