# Generated by Django 5.2.5 on 2025-08-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0006_alter_dds_category_alter_dds_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choicecategory',
            old_name='category_choice',
            new_name='choice_value',
        ),
        migrations.RenameField(
            model_name='choiceoperationtype',
            old_name='operation_type_choice',
            new_name='choice_value',
        ),
        migrations.RenameField(
            model_name='choicestatus',
            old_name='status_choice',
            new_name='choice_value',
        ),
        migrations.RenameField(
            model_name='choicesubcategory',
            old_name='subcategory_choice',
            new_name='choice_value',
        ),
    ]
